### ISSUE TITLE
Nieuwe HTML voor nieuw ontwerp

### ISSUE THREAD

**Issue by julia-stevens** [julia-stevens/your-tribe-profile-card#3]
![bouwplan schets](https://github.com/user-attachments/assets/7a25d1d1-b267-4252-87f4-bc05bb90dc53)

**Comment by KoopReynders** [comment]
Je kan een `<main>` om de belangrijkste content zetten. De `<figure>` lijkt me een goede oplossing. Of de 2 sections aan de zijkanten een section zijn weten we nog niet. Check de MDN HTML reference voor wat voor 'content sectioning' je zou kunnen gebruiken.
